// Code generated by coz. DO NOT EDIT.
/**
 * controller-mixin helpers
 * @module helpers
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get getAllPropertyDescriptors () { return _d(require('./getAllPropertyDescriptors')) },
  get instanceMethodNamesFor () { return _d(require('./instanceMethodNamesFor')) },
}
