// Code generated by coz. DO NOT EDIT.
/**
 * Mixins for the-controller
 * @module the-controller-mixins
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get compose () { return _d(require('./compose')) },
  get helpers () { return _d(require('./helpers')) },
  get withAuthorized () { return _d(require('./withAuthorized')) },
  get withClient () { return _d(require('./withClient')) },
  get withDebug () { return _d(require('./withDebug')) },
  get withListen () { return _d(require('./withListen')) },
  get withPreference () { return _d(require('./withPreference')) },
  get withSeal () { return _d(require('./withSeal')) },
}
